const COUNTRY_FLAGS: Record<string, string> = {
  "United Kingdom": "🇬🇧",
  UK: "🇬🇧",
  "United States": "🇺🇸",
  US: "🇺🇸",
  USA: "🇺🇸",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Portugal: "🇵🇹",
  Netherlands: "🇳🇱",
  Switzerland: "🇨🇭",
  Australia: "🇦🇺",
  Canada: "🇨🇦",
  Japan: "🇯🇵",
  Singapore: "🇸🇬",
  Ireland: "🇮🇪",
  Italy: "🇮🇹",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Denmark: "🇩🇰",
  Finland: "🇫🇮",
  "New Zealand": "🇳🇿",
  "Hong Kong": "🇭🇰",
  UAE: "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  India: "🇮🇳",
  Brazil: "🇧🇷",
  Mexico: "🇲🇽",
  "South Korea": "🇰🇷",
  Thailand: "🇹🇭",
  Malaysia: "🇲🇾",
  Indonesia: "🇮🇩",
  Philippines: "🇵🇭",
  Poland: "🇵🇱",
  "Czech Republic": "🇨🇿",
  Greece: "🇬🇷",
  Israel: "🇮🇱",
  "South Africa": "🇿🇦",
};

export function getFlag(country: string): string {
  return COUNTRY_FLAGS[country] || "🏳️";
}
